apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-urlmanager-db
  labels:
    app: pg-urlmanager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-urlmanager-db
  template:
    metadata:
      labels:
        app: pg-urlmanager-db
    spec:
      containers:
      - name: postgres-container
        image: postgres:17.6 
        env:
        - name: POSTGRES_DB 
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret 
              key: DB_NAME 
        - name: POSTGRES_USER 
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret 
              key: DB_USERNAME 
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret 
              key: DB_PASSWORD 
        ports:
          - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-storage
            subPath: urlmanager
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: pg-urlmanager-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1 
kind: Service 
metadata:
  name: pg-urlmanager-db 
  labels:
    app: pg-urlmanager-db
spec:
  ports:
    - name: pgsql-service
      port: 5432 
      targetPort: 5432 
      protocol: TCP 
  type: ClusterIP 
  selector:
    app: pg-urlmanager-db 
