apiVersion: v1
kind: Secret
metadata:
  name: urlmanager-db-secret
  labels:
    app: pg-urlmanager-db
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: TnV0YW5peC80dQ==
  DB_NAME: dXJsbWFuYWdlcg==
  DB_HOST: cGctdXJsbWFuYWdlci1kYg==
