apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlmanager-app
  labels:
    app: urlmanager-app
    full-app: urlmanager
    version: 0.0.41
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urlmanager-app
  template:
    metadata:
      creationTimestamp: "2025-11-05T10:00:00Z"
      labels:
        app: urlmanager-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - urlmanager-app
              topologyKey: topology.kubernetes.io/zone
      containers:
      - name: urlmanager-app
        image: ghcr.io/vedw/urlmanager:0.0.41
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: urlmanager-db-secret
              key: DB_HOST
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IMAGE_TAG
          value: 0.0.41
---
apiVersion: v1
kind: Service
metadata:
  name: urlmanager-app-service
  labels:
    app: urlmanager-app
    full-app: urlmanager
spec:
  selector:
    app: urlmanager-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: urlmanager-gateway
  labels:
    app: urlmanager-app
    full-app: urlmanager
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: urlmanager-route
  labels:
    app: urlmanager-app
    full-app: urlmanager
spec:
  parentRefs:
  - name: urlmanager-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: urlmanager-app-service
      port: 80
